name: "PR workflow"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'static/**'
      - '**.md'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - 'fastlane/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      signpath_sign:
        description: 'sign binary by signpath'
        required: false
        default: false
        type: boolean
      run_android:
        description: 'manually run android build'
        required: false
        default: false
        type: boolean

jobs:
  changes:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: read
    outputs:
      android: ${{ steps.filter.outputs.android }}
      flutter: ${{ steps.filter.outputs.flutter }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          predicate-quantifier: 'every'
          filters: |
            android:
              - 'android/**'
            flutter:
              - 'lib/**'
              - 'pubspec.yaml'
              - 'assets/**'

  flutter-build-android:
    needs: changes
    # 逻辑：如果是手动触发 OR (不是草稿 AND (修改了安卓原生配置 OR 修改了Flutter业务代码))
    if: ${{ github.event.inputs.run_android || (! github.event.pull_request.draft && (needs.changes.outputs.android == 'true' || needs.changes.outputs.flutter == 'true')) }}
    name: "Release for android"
    runs-on: "ubuntu-latest"
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libasound2-dev
        shell: bash
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
        
      - name: Print Flutter version
        run: flutter doctor -v
        shell: bash
        
      - name: Build Flutter for Android
        # 指定只构建 arm (v7a) 和 arm64 (v8a)
        run: flutter build apk --split-per-abi --target-platform android-arm,android-arm64
        shell: bash
        
      - name: Package android build output
        # 将生成的两个包重命名并移动，方便后续上传
        run: |
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk Kazumi_canary_v7a.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk Kazumi_canary_v8a.apk
        shell: bash

      # 步骤1：单独上传 v7a
      - name: Upload android v7a output
        uses: actions/upload-artifact@v4
        with:
          name: Kazumi_canary_v7a
          path: Kazumi_canary_v7a.apk
          retention-days: 3

      # 步骤2：单独上传 v8a
      - name: Upload android v8a output
        uses: actions/upload-artifact@v4
        with:
          name: Kazumi_canary_v8a
          path: Kazumi_canary_v8a.apk
          retention-days: 3
